'''Given two strings ‘a’ and ‘b’, where ‘b’ is generated by randomly shuffling ‘a’ and adding one more 
letter at some random position. Find that extra letter.'''

# code 1

a = input()
b = input()

a = ''.join(sorted(a))
b = ''.join(sorted(b))
c = b
b = b[:-1]

if a==b :
    print(c[len(b)])

else :
    for i in range(len(a)) :
        if (a[i]!=b[i]) :
                print(b[i])
                break
            



# code 2

a = input()
b = input()

a = ''.join(sorted(a))
b = ''.join(sorted(b))

ans = False

for i in range(len(a)) :
    if (a[i]!=b[i]) :
            print(b[i])
            ans = True
            break

if ans == False :
    print(b[len(b)-1])
